params [["_direction", 0, [0]]];
private _result = [] call ACME_fnc_getSelectedInfusionEntryIndexes;
if (_result isEqualTo []) exitWith {};
_result params ["_patient", "_indexes"];
if (_indexes isEqualTo []) exitWith {};
private _entries = _patient getVariable ["ACME_infusion_BagMedications", []];
private _entry = _entries select (_indexes select 0);
private _drops = _entry param [21,0];
private _step = if (_drops < 20) then {1} else {5};
_drops = ((_drops + _direction * _step) max ACME_infusion_minDropsPerMinute) min ACME_infusion_maxDropsPerMinute;
private _pos = [_drops] call ACME_fnc_dropsToClampPosition;
[_patient, "infusionClamp", [_patient, _indexes apply {(_entries select _x) select 0}, [_patient] call ACME_fnc_clinicalEpoch, _pos, -1]] call ACME_fnc_ownerDispatch;
uiNamespace setVariable ["ACME_RollerClamp_Position", _pos];
[] call ACME_fnc_updateClampDialog;
