#!/usr/bin/env python3
"""NA7 source contracts and preservation checks. Does not compile or execute SQF."""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
from source_scan import lex, render

def run(root: Path, baseline: Path | None = None) -> dict:
    checks=[]
    def read(p):return (root/p).read_text(encoding='utf-8-sig')
    def fn(n):return read('functions/fn_'+n+'.sqf')
    def check(name,value,detail=''):checks.append(dict(name=name,passed=bool(value),detail=detail))
    cfg=read('config.cpp');post=fn('postInit')
    check('versions_agree','version = "0.9.999r-73-NA7";' in cfg and 'ACME_infusion_version = "0.9.999r-73-NA7";' in post)
    new=['givePremixedSet','pressureInfuserCan','reopenTransfusion','skClickSound','skClose','skIMGeometry','skListRefresh','skListSelect','skSiteClick','skSiteGeometry','skUiTick']
    check('new_function_registrations_once',all(len(re.findall(r'\bclass\s+'+n+r'\s*\{',cfg))==1 and (root/('functions/fn_'+n+'.sqf')).is_file() for n in new))
    op=fn('openDrawMenu');si=fn('skInject');cl=fn('skClose');done=fn('infusionDone')
    check('prep_passes_patient','objNull, ""] call ACME_fnc_skOpenDraw' not in op and 'call ACME_fnc_skOpenDraw' in op)
    check('both_prep_contexts_return','["active", "prepared"]' in si and 'ACME_SK_Return' in si)
    check('single_unload_owner','["Unload", {_this call ACME_fnc_skClose}]' in si)
    check('return_uses_captured_patient','_display getVariable ["ACME_SK_Return", []]' in cl and 'ACME_fnc_reopenTransfusion' in cl)
    check('ordinary_narc_return_uses_patient','[_patient, "medication"] call ACME_fnc_reopenMedicalMenu' in cl)
    check('size_switch_does_not_return','if (_switch) exitWith {};' in cl)
    check('done_closes_exact_draw_display','findDisplay 84000' in done and 'closeDisplay' in done and 'reopenMedicalMenu' not in done)
    check('return_avoids_other_open_dialog','{dialog}' in fn('reopenTransfusion'))
    check('tally_ids_no_body_collision','84360' in fn('patchDrawDialog') and '84361' in fn('infusionRefreshTally') and '84160' not in fn('patchDrawDialog'))
    pre=fn('givePremixedSet');rq=fn('preparedAttachRequest');lo=fn('preparedAttachLocal');ack=fn('preparedAttachAck')
    check('premix_real_drug_type_gate','ACME_infusion_premixedByType' in fn('hangPreparedSet') and 'ACME_fnc_givePremixedSet' in fn('hangPreparedSet'))
    check('premix_preserves_partial_dose','_dose * ((_remaining / _volume) min 1)' in pre)
    check('premix_clamp_and_drop_initial_zero','ACME_infusion_defaultDropSet, 0, 0' in pre)
    check('staged_custody_retained_before_request','deleteAt' not in pre and 'ACME_fnc_preparedAttachRequest' in pre)
    check('close_source_before_owner_can_ack',rq.index('_source closeDisplay')<rq.index('call ACME_fnc_ownerDispatch'))
    check('request_serial_and_inflight_guard','ACME_preparedRequestSerial' in rq and 'values _inflight' in rq)
    check('owner_epoch_and_access_validated','!local _patient' in lo and '_epoch == ([_patient] call ACME_fnc_clinicalEpoch)' in lo and 'ACME_fnc_isYLineAccess' in lo)
    check('staged_site_occupancy_checked','_occupied < 0' in lo)
    check('single_premix_registration','false, true] call ace_medical_treatment_fnc_ivBagLocal' in lo and 'call ACME_fnc_infusionRegisterLocal' in lo)
    check('native_premix_defer_flag','_deferPremixed' in read('overrides/fn_ivBagLocal.sqf'))
    check('native_discovered_premix_closed','_ctx, _med, _dose, -1, -1, 0, 0' in fn('syncPremixedBags'))
    check('staged_failure_retains_set','The premixed set was not attached. It remains in Prepared IV sets.' in ack)
    check('ack_does_not_steal_new_dialog','if (dialog) exitWith' in ack)
    check('ack_waits_for_replicated_dose','CBA_fnc_waitUntilAndExecute' in ack and 'ACME_RollerClamp_Context' in ack)
    check('roller_selection_by_stable_ids','_ids' in fn('getSelectedInfusionEntryIndexes') and 'ACME_fnc_clinicalEpoch' in fn('getSelectedInfusionEntryIndexes'))
    u=fn('updateTransfusionControls');sel=fn('getSelectedActiveBagContext')
    check('two_pressure_buttons','86148' in u and '86149' in u and 'Pressure Infuse' in cfg)
    check('infusion_pressure_below_move_remove','[[_ctrlInfMove, 0], [_ctrlInfRemove, 1], [_ctrlInfPressure, 2]]' in u)
    check('selection_tracks_mouse_and_focus',all(x in u for x in ['MouseEnter','MouseButtonDown','SetFocus','ACME_txActivePane']))
    check('programmatic_rebuild_guard','ACME_txRebuilding' in u)
    check('selection_uses_list_value','_list lbValue _row' in sel and '_pane in ["transfusion", "infusion"]' in sel)
    check('hang_rechecks_transfusion_context','!= "transfusion"' in fn('hangBagFromMenu') and 'ACME_infusion_BagMedications' in fn('hangBagFromMenu'))
    tx=u[u.index('if (_txSelected) then {'):u.index('if (!isNull _ctrlHang)',u.index('if (_txSelected) then {'))]
    check('menu_guard_uses_declared_patient','_patient getVariable' not in tx and '_targetPatient getVariable' in tx and u.index('private _targetPatient')<u.index('if (_txSelected)'))
    check('cuff_gate_distinguishes_medicated_bag','_hasDrug == _infusion' in fn('pressureInfuserCan'))
    check('owner_cuff_guard_distinguishes_medicated_bag','_allowDrug' in fn('pressureInfuserCommit'))
    check('full_native_medical_group','["ace_medical_gui_BodyImage", 84140]' in si and 'call ace_medical_gui_fnc_updateBodyImage' in si)
    check('body_patient_bound_to_display','ACME_SK_ReturnPatient' in fn('skBuildHotspots') and 'ACME_SK_ReturnPatient' in fn('skSiteClick'))
    check('body_dynamic_art_created_before_inputs',si.index('call ace_medical_gui_fnc_updateBodyImage')<si.index('forEach _inputs'))
    geometry=lambda n:json.loads(fn(n).split("*/",1)[1].strip())
    check('native_geometry_19_vascular_4_im',len(geometry('skSiteGeometry'))==19 and len(geometry('skIMGeometry'))==4)
    check('exact_site_rechecked','[_p, _part, 0, _site] call ACM_circulation_fnc_hasIV' in fn('skSiteClick') and '[_p, _part, 0] call ACM_circulation_fnc_hasIO' in fn('skSiteClick'))
    hot=fn('skBuildHotspots')
    check('shared_im_blue_for_vascular','ACME_SK_IMColor' in hot and 'then {1} else {0.42}' in hot)
    check('icon_bounds_two_pixel_tolerance','_u * _bw - 2 * pixelW' in hot and '_w * _bw + 4 * pixelW' in hot)
    check('im_native_skin_tinted_below_devices','if (_show) then {_image ctrlSetTextColor _tint;};' in hot and 'ctrlCreate' not in hot)
    check('route_restores_native_clinical_colors','ACME_SK_LastRoute' in hot and 'call ace_medical_gui_fnc_updateBodyImage' in hot)
    check('save_uses_old_inject_rectangle','ctrlPosition (_display displayCtrl 84005)' in si and '(_display displayCtrl 84004) ctrlSetPosition' in si)
    check('draw_sound_keeps_click_transactions','84003) ctrlAddEventHandler ["MouseButtonDown"' in si and '84003) ctrlAddEventHandler ["KeyDown"' in si)
    check('draw_uses_local_standard_sound','playSoundUI' in fn('skClickSound') and '"RscButton" >> "soundClick"' in fn('skClickSound'))
    ls=fn('skListSelect');lr=fn('skListRefresh');tick=fn('skUiTick')
    check('missing_item_cannot_change_selection',ls.index('if (!_available) exitWith')<ls.index('_list lbSetCurSel'))
    check('native_medication_backing_retained','_list lbData _i' in lr and 'ACME_SK_Row' in lr and 'lbClear' not in lr)
    check('row_input_includes_image','_button ctrlSetPosition [0, _forEachIndex * _rowH, _innerW, _rowH]' in lr)
    check('rows_reconciled_without_global_teardown','Reconcile only changed rows' in lr and '_row set [0, +_spec]' in lr)
    check('two_red_windows','_elapsed < 0.09' in tick and '_elapsed >= 0.18 && {_elapsed < 0.27}' in tick)
    check('missing_row_survives_both_flashes','diag_tickTime - _at < 0.36' in lr)
    check('green_pulses_for_both_choices','case "size"' in tick and 'case "medication"' in tick and '[0.12,0.75,0.25,_alpha]' in tick)
    check('body_and_feedback_poll_local','_now + 0.1' in tick and '_now + 0.2' in tick and '0.04, [_display]' in si)
    local_files=['skUiTick','skBuildHotspots','skListRefresh','skListSelect','skClickSound']
    check('new_presentation_never_broadcasts',all(not any(t in render(lex(fn(n))) for t in ['remoteExec','CBA_fnc_globalEvent','CBA_fnc_targetEvent','publicVariable']) for n in local_files))
    check('display_loop_removed_on_close','ACME_SK_PulsePFH' in cl and 'CBA_fnc_removePerFrameHandler' in cl)
    if baseline:
        sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
        same=lambda paths:all((root/p.relative_to(baseline)).is_file() and sha(p)==sha(root/p.relative_to(baseline)) for p in paths)
        assets=[p for p in baseline.rglob('*') if p.suffix.lower() in {'.paa','.ogg','.wss','.wav','.p3d','.rtm'}]
        chest=list((baseline/'functions').glob('fn_chestSeal*.sqf'))
        check('all_original_assets_identical',same(assets),str(len(assets)))
        check('live_chest_seal_functions_identical',same(chest),str(len(chest)))
        check('na6_dropdown_renderer_unchanged',same([baseline/'overrides/fn_updateActions.sqf']))
        check('na6_settings_and_hardcore_unchanged',same([baseline/p for p in ['XEH_preInit.sqf','XEH_settings.hpp','functions/fn_applyHardcore.sqf']]))
        check('postinit_only_version_changed',post==(baseline/'functions/fn_postInit.sqf').read_text().replace('0.9.999r-73-NA6','0.9.999r-73-NA7'))
    return dict(scope=__doc__,passed=sum(x['passed'] for x in checks),failed=sum(not x['passed'] for x in checks),checks=checks)

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('addon',type=Path);ap.add_argument('--baseline',type=Path);ap.add_argument('--json',type=Path);args=ap.parse_args();r=run(args.addon,args.baseline)
    if args.json:args.json.write_text(json.dumps(r,indent=2)+'\n')
    for c in r['checks']:print(('PASS ' if c['passed'] else 'FAIL ')+c['name']+(' '+c['detail'] if c['detail'] else ''))
    print(f"{r['passed']} passed, {r['failed']} failed. Source checks only.")
    return bool(r['failed'])
if __name__=='__main__':raise SystemExit(main())
