#!/usr/bin/env python3
"""Generate the right-arm row profiles from shipped PAA alpha silhouettes.

The selected limb is followed row by row from measured vein seeds in ivSiteData,
using overlap with the preceding arm run. This excludes the separate torso strip.
The reliable span stops before shoulder fusion or finger separation. The compact
polyline stays within one 1024-mip pixel of both measured edges at every row.
Run with --write to regenerate fn_ivLimbBounds.sqf, or --check to verify it.
"""
from pathlib import Path
import argparse
import math
import re
import numpy as np
from paa import read_paa

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'functions' / 'fn_ivLimbBounds.sqf'
PROFILES = (
    ('iv_right_arm_ca', ('middle', 'lower'), .26, .79),
    ('iv_right_arm_rear_ca', ('upper',), .22, .79),
)
MIP = 1024
ALPHA_THRESHOLD = 128
MAX_EDGE_ERROR = 1 / MIP


def catalog_seeds(root=ROOT):
    source = (root / 'functions' / 'fn_ivSiteData.sqf').read_text(encoding='utf-8-sig')
    seeds = {}
    for site, row in re.findall(r'\["rightarm#(\w+)",\s*\[([^\]]+)\]\]', source):
        values = re.findall(r'"[^"]*"|[-\d.]+', row)
        seeds[site] = (float(values[4]), float(values[5]))
    return seeds


def opaque_runs(alpha_row):
    changes = np.diff(np.r_[False, alpha_row >= ALPHA_THRESHOLD, False].astype(int))
    # Ignore isolated bevel-sized noise; the narrowest reliable arm is > 50 px.
    return [(int(a), int(b)) for a, b in zip(np.flatnonzero(changes == 1),
                                            np.flatnonzero(changes == -1)) if b - a >= 8]


def measured_rows(texture, sites, min_v, max_v, root=ROOT, want=MIP):
    _, alpha = read_paa(root / 'ui' / 'iv' / (texture + '.paa'), want=want)
    height, width = alpha.shape
    seeds = catalog_seeds(root)
    seed_u, seed_v = seeds[sites[0]]
    first = math.ceil(min_v * height - .5)
    last = math.floor(max_v * height - .5)
    seed_row = min(last, max(first, int(seed_v * height)))
    candidates = [run for run in opaque_runs(alpha[seed_row])
                  if run[0] <= seed_u * width < run[1]]
    if len(candidates) != 1:
        raise ValueError(f'{texture}: seed does not identify one arm run')
    chosen = {seed_row: candidates[0]}
    for step, limit in ((1, last + 1), (-1, first - 1)):
        previous = chosen[seed_row]
        for row in range(seed_row + step, limit, step):
            candidates = opaque_runs(alpha[row])
            scored = sorted(((max(0, min(b, previous[1]) - max(a, previous[0])), a, b)
                             for a, b in candidates), reverse=True)
            if not scored or scored[0][0] < (previous[1] - previous[0]) * .5:
                raise ValueError(f'{texture}: arm continuity lost at row {row}')
            _, left, right = scored[0]
            previous = chosen[row] = (left, right)
    # Every catalog seed on this view must land in the SAME tracked limb.
    for site in sites:
        u, v = seeds[site]
        left, right = chosen[int(v * height)]
        if not left <= u * width < right:
            raise ValueError(f'{texture}: tracked component missed {site} seed')
    return np.array([[(row + .5) / height, chosen[row][0] / width,
                      chosen[row][1] / width] for row in range(first, last + 1)])


def simplify(rows, tolerance=MAX_EDGE_ERROR):
    """Keep a vertex wherever either interpolated edge exceeds the error budget."""
    keep = {0, len(rows) - 1}
    pending = [(0, len(rows) - 1)]
    while pending:
        a, b = pending.pop()
        if b - a < 2:
            continue
        fraction = (rows[a + 1:b, 0] - rows[a, 0]) / (rows[b, 0] - rows[a, 0])
        predicted = rows[a, 1:] + fraction[:, None] * (rows[b, 1:] - rows[a, 1:])
        errors = np.max(np.abs(rows[a + 1:b, 1:] - predicted), axis=1)
        index = int(np.argmax(errors))
        if errors[index] > tolerance + 1e-12:
            middle = a + 1 + index
            keep.add(middle)
            pending.extend(((a, middle), (middle, b)))
    return rows[sorted(keep)]


def render(root=ROOT):
    sections = []
    for texture, sites, min_v, max_v in PROFILES:
        profile = simplify(measured_rows(texture, sites, min_v, max_v, root))
        entries = ',\n'.join('            [' + ', '.join(f'{value:.7f}' for value in row) + ']'
                              for row in profile)
        sections.append(f'    case "\\acm_extended\\ui\\iv\\{texture}.paa": {{\n'
                        f'        [\n{entries}\n        ]\n    }};')
    return '''/* Cursor-height limb edges for the patient right arm, in body-canvas UV.
   [_bodyPart, _viewTexture, _v] call ACME_fnc_ivLimbBounds -> [leftU,rightU] or [].
   Generated by tools/generate_iv_limb_bounds.py from PAA alpha >= 128 at 1024 mip.
   Tracks the arm run from ivSiteData vein seeds, excluding the separate torso strip.
   Front: v .26-.79; rear: v .22-.79, trimmed to pixel-center rows. Outside these
   reliable spans (shoulder joins / finger splits), return [] for the caller fallback.
   Linear interpolation error <= one mip pixel at every measured row. No state writes.
   Families, anchors, insertion axes and rotation signs are deliberately untouched. */
params [["_bodyPart", "", [""]], ["_viewTexture", "", [""]], ["_v", -1, [0]]];
if (toLower _bodyPart != "rightarm" || {!finite _v}) exitWith {[]};
private _profile = switch (toLower _viewTexture) do {
''' + '\n'.join(sections) + '''
    default {[]};
};
if (count _profile < 2) exitWith {[]};
if (_v < ((_profile select 0) select 0) || {_v > ((_profile select ((count _profile) - 1)) select 0)}) exitWith {[]};
private _index = _profile findIf {(_x select 0) >= _v};
if (_index <= 0) exitWith {(_profile select 0) select [1,2]};
(_profile select (_index - 1)) params ["_v0", "_left0", "_right0"];
(_profile select _index) params ["_v1", "_left1", "_right1"];
private _fraction = (_v - _v0) / (_v1 - _v0);
[_left0 + (_left1 - _left0) * _fraction, _right0 + (_right1 - _right0) * _fraction]
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--write', action='store_true')
    group.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding='utf-8')
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
        raise SystemExit('Right-arm profile differs from its measured source; regenerate with --write')
    for texture, sites, min_v, max_v in PROFILES:
        rows = measured_rows(texture, sites, min_v, max_v)
        profile = simplify(rows)
        error = max(np.max(np.abs(np.interp(rows[:, 0], profile[:, 0], profile[:, edge]) - rows[:, edge]))
                    for edge in (1, 2))
        print(f'{texture}: {len(profile)} vertices, {len(rows)} measured rows, max edge error {error:.7f} U')


if __name__ == '__main__':
    main()
