#define ACM_GUI_AED_SIZEM 1.05
#define ACM_GUI_AED_GRID_W (ACM_UI_CANVAS_W * 0.55)
#define ACM_GUI_AED_GRID_H (ACM_GUI_AED_GRID_W * 4/3)
#define ACM_GUI_AED_GRID_X (ACM_UI_CANVAS_X + (ACM_UI_CANVAS_W - (ACM_GUI_AED_GRID_W * ACM_GUI_AED_SIZEM)) / 2)
#define ACM_GUI_AED_GRID_Y (ACM_UI_CANVAS_Y + (ACM_UI_CANVAS_H - (ACM_GUI_AED_GRID_H * ACM_GUI_AED_SIZEM)) / 2)

#define ACM_AED_pxToScreen_X(X) (X / 2048 * ACM_GUI_AED_GRID_W + ACM_GUI_AED_GRID_X)
#define ACM_AED_pxToScreen_Y(X) (X / 2048 * ACM_GUI_AED_GRID_H + ACM_GUI_AED_GRID_Y)
#define ACM_AED_pxToScreen_W(X) (X / 2048 * ACM_GUI_AED_GRID_W)
#define ACM_AED_pxToScreen_H(X) (X / 2048 * ACM_GUI_AED_GRID_H)
